add search history with shared preferences
Shchegolyaeva/PlayListMaker2 pull request #6
Opened 2023-03-01 12:16 UTC by Shchegolyaeva

2023-03-01 17:46 UTC, NoDopezzz requested changes

2023-03-01 17:46 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/App.kt
> +    fun isDarkMode(context: Context): Boolean {
⏫ Так как `Application` является реализацией класса `Context` в метод `isDarkMode` не обязательно передавать аргумент `context` и можно вызвать `resources` напрямую

2023-03-01 17:46 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +            historySearchGroup.visibility = if (hasFocus && inputEditText.text.isEmpty()) View.VISIBLE else View.GONE
⏫ Чтобы упростить смену видимости элемента можно использовать extension-метод `isVisible`
`isVisible = true` соответствует `visibility = View.VISIBLE`
`isVisible = false` соответствует `visibility = View.GONE`

2023-03-01 17:46 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +    private lateinit var historySearchGroup: ConstraintLayout
⚠️ Стоит обратить внимание на синхронизацию состояний экрана при ошибке и показе истории запросов. Если попробовать ввести пустой запрос и мы очевидно ничего не найдем. В таком случае у нас будет показана и экран с ошибкой и история запросов

<img width="385" alt="image" src="https://user-images.githubusercontent.com/56832972/222215353-7a474af4-8425-4ee5-91b2-bb6bcdcd5cc4.png">

2023-03-01 17:46 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +                historySearchGroup.visibility = if (historySearchGroup.hasFocus() && p0?.isEmpty() == true) View.VISIBLE else View.GONE
⚠️ Контейнер `historySearchGroup` не будет получать фокус, если его дочерний элемент находится в фокусе. Поэтому, если мы захотим удалить текст из поля ввода, историю запросов увидеть не получится из-за условия `historySearchGroup.hasFocus()`

2023-03-01 17:46 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +            searchHistory.add(track)
⚠️ Когда мы добавляем будем кешировать новый трек в историю запросов мы должны также подумать о его отображении на экране, когда пользователь захочет очистить свой запрос

⏫ Как и в случае с реализацией очистки истории нам всегда приходится думать о двух источниках правды: список треков в адаптере и список треков в `SharedPreferences`. Чтобы упростить нам жизнь, мы можем воспользоваться слушателем на изменения значений в SharedPreferences, который был рассмотрен в текущем спринте, и в зависимости от изменений обновлять список треков в адаптере. А при клике на кнопку "Очистить" и элемент фрагмента изменять только значение в `SharedPreference`. 
Таким образом мы реализуем паттерн `Observer` и будем "слушать" изменения кеша!

2023-03-01 17:46 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SettingsActivity.kt
> +        //     val switchTheme = findViewById<Switch>(R.id.switch_theme)
⏫ Лучше не оставлять закомменченный код в итоговой реализации)

2023-03-01 17:46 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +            historySearchGroup.visibility = if (hasFocus && inputEditText.text.isEmpty()) View.VISIBLE else View.GONE
⚠️ Также стоит проверять, пустая ли история запросов перед показом кнопки "Очистить историю"

2023-03-02 14:19 UTC, Shchegolyaeva commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +            searchHistory.add(track)
Привет, не получилось реализовать регистер SharedPreference, тк описано в теории спринта.
Регистер постоянно удалялся сбощиком мусора, подробнее тут: https://stackoverflow.com/questions/2542938/sharedpreferences-onsharedpreferencechangelistener-not-being-called-consistently

Пришлось реализовать интерфейс OnSharedPreferenceChangeListener и добавить в код sharedPrefs.registerOnSharedPreferenceChangeListener(this)

Почему, не срабатывает так как говорят в теории, просто добавив работу с анонимным классом?

2023-03-02 18:49 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +            searchHistory.add(track)
Интересно, не знал про такие детали) Действительно проблема с тем, что мы передаем анонимный класс и он сохраняется внутри слабой ссылки. Но из-за того, что этот созданный объект никто не хранит кроме `SharedPreferences`, он вскоре будет удален. Чтобы детальнее понять причину такого поведения, стоит изучить разницу типов ссылок в Java/Kotlin:

- Сильная ссылка - ссылка на объект, который будет удален сборщиком мусора только тогда, когда ссылка будет уничтожена. 
Создаем мы такой объект обычным присваиванием: `var object = SomeObject()`
GC будет готов его удалить из памяти, например когда мы вручную обнулим ссылку на него: `var object = null` или когда объект, который хранит в себе этот объект будет удален по тому же принципу
- Слабая ссылка - ссылка на объект, который будет удален тогда, когда на нее будут отсутствовать сильные ссылки. Такой объект мы можем создать через 
```
val object = Object()
val objectWeak = WeakReference(object)
```

Это значит, что когда object будет удален, то и objectWeak тоже будет удален. 
- Мягкая ссылка - почти как слабая, но GC удалит ссылку, когда не будет сильной ссылки на объект и ему будет сильно не хватать памяти.

(Есть еще фантомная ссылка, но ее редко используют).
Можно почитать на JavaRush подробнее [про типы ссылок ](https://javarush.com/groups/posts/1267-otlichija-mezhdu-slabihmi-mjagkimi-fantomnihmi-i-obihchnihmi-ssihlkami-v-java)

Это значит, что нам обязательно хранить ссылку на слушатель в нашей `SearchActivity` через
`val listener = object : OnSharedPreferenceChangeListener { ... }`

или же твой вариант с реализацией слушателя самой `Activity`. 

Нужно всегда помнить о необходимости чистить слушатели в `onDestroy`, чтобы избежать утечки памяти.

Надеюсь, понятно рассказал. Если возникнут вопросы, можешь обращаться к наставнику)

2023-03-02 18:49 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +            searchHistory.add(track)
PS: передам коллегам, чтобы отметили в курсе этот неочевидный момент. Спасибо!

2023-03-05 17:29 UTC, merged